dataset:
  _target_: torchvision.datasets.CIFAR10
  train: true
  download: true
  root: ${data_dir}

dataset_eval:
  _target_: torchvision.datasets.CIFAR10
  train: false
  download: true
  root: ${data_dir}

wrapper_train:
  _target_: utils.vision_utils.OpenFlamingoVisualFeaturesCache
  cache_path: ${data_dir}/representations/cifar10_train.pth

wrapper_eval:
  _target_: utils.vision_utils.OpenFlamingoVisualFeaturesCache
  cache_path: ${data_dir}/representations/cifar10_eval.pth

input_dim: 768
K: 10
name: cifar10
