defaults:
    - base
    - optimization : optimization_default
    - reward : openflamingo
    - template : openflamingo_imageclassification
    - dataset: cifar100_clip_emb
    - labelset: cifar100_openflamingo
    - dataset_transforms: openflamingo
    - task_encoder: openflamingo_lora
    - _self_

optimization:
    lr_schedule_name: cosine
    lr_schedule:
        warmup_iters: 500
        lr: 1e-4
        final_lr: 1e-6
        iters: ${num_iterations}

batch_size: 32
batch_size_eval: 100
N: 16
num_iterations: 3000
